### ISSUE TITLE
Testing checklist for next release

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#329]
- [x] Log in as admin should redirect to dashboard #330 
- [x] Log in as normal should not
- [x] Dashboard feature works as expected (latest events first, all events shown)
- [x] Facebook sharing is improved. #159 
- [x] published flag #331 
- [x] cancel highlighted events #328 
- [x] bigger pictures in highlights #335
- [x] Weekly sidebar working ok? #333 
- [x] Mobile view improved? #294

**Comment by Siggik** [comment]
jeg tjekker det nu. Her er tjeklisten @tadoh.

**Comment by Siggik** [comment]
Jeg er kommet hele vejen ned til Weekly sidebar working ok?. Indtil her ser det alt ud til at virke som det det skal. Men da prøvede at oprette dette event:

![screenshot from 2016-04-06 20 13 24](https://cloud.githubusercontent.com/assets/7570153/14327825/4acdaab6-fc34-11e5-808f-ee2368386828.png)

Fik jeg denne fejlbesked: 

"We're sorry, but something went wrong.

If you are the application owner check the logs for more information."

**Comment by Siggik** [comment]
By the way: I forhold til Weekly sidebar drømmer jeg stadig om kortere afstand op til ugedagen for de events der høre til uge dagen:)

**Comment by Siggik** [comment]
Hvis jeg prøver at gå på staging på mobilen får jeg også denne fejlbesked: ""We're sorry, but something went wrong.

If you are the application owner check the logs for more information.""

**Comment by Siggik** [comment]
How det er hvis hele siden der er nede nu.... jeg nåede ikke at tjekke ordentlig det med facebook før.

**Comment by ronan-mch** [comment]
> I forhold til Weekly sidebar drømmer jeg stadig om kortere afstand op til ugedagen for de events der høre til uge dagen:)

jeg har lavet det kortere - er det ikke nok?

mht. fejlen kan jeg lige genskabe det. Jeg prøver lige igen...

**Comment by tadoh** [comment]
Har lige leget med det lidt. Synes alt fungerer smooth. Rigtigt godt arbejde!

Der er nogle mindre ting, som er mere ideer end problemer:

* Det er fedt at man ser kalenderen på mobilen nu, men kan slet ikke se gentagende begivenheder. Er det med vilje? Kunne være fedt at kunne slå dem til eller noget.
* Når man oprettet en event, kan man ikke redigere det til at blive en gentagende event. Det skete fx for mig, da jeg prøvede at oprette en gentagende event men glemte at tjekke checkboxen. Man skal slette eventet for at kunne lave den om til en gentagende event.
* Gentagende events der ikke starter med det samme dukker slet ikke op på kalenderen. Man kan evt overveje at få dem til at dukke op med en "[fra den 3. maj]" tekst eller noget...

**Comment by tadoh** [comment]
> jeg har lavet det kortere - er det ikke nok?
mht. fejlen kan jeg lige genskabe det og sitet virker ok for mig. Jeg prøver lige igen...

Tænker godt det kunne være kortere mellem mandag og den første event, så de holder bedre sammen

**Comment by ronan-mch** [comment]
@Siggik - jeg kan godt se fejl beskeden i logs men kan desværre ikke genskabe den, selvom jeg prøver med de samme data som står i dit billede. Er du sød at prøve igen og se om den gentages? Det er sådan nogle ting der virkelig gøre mig nervøs...

> Det er fedt at man ser kalenderen på mobilen nu, men kan slet ikke se gentagende begivenheder. Er det med vilje? Kunne være fedt at kunne slå dem til eller noget.

Ja, det var det simpleste. Måske kunne jeg lave en dropdown eller noget til dem i stedet...

**Comment by tadoh** [comment]
> Måske kunne jeg lave en dropdown eller noget til dem i stedet...

Jo, det kunne fungere fint.

**Comment by Siggik** [comment]
> @Siggik - jeg kan godt se fejl beskeden i logs men kan desværre ikke genskabe den, selvom jeg prøver med de samme data som står i dit billede. Er du sød at prøve igen og se om den gentages? Det er sådan nogle ting der virkelig gøre mig nervøs...

Nu har jeg prøvet at genskabe fejlen. Det lykkedes. 10.48 i dag med disse infos: 

![fejl](https://cloud.githubusercontent.com/assets/7570153/14345703/c6389a24-fcae-11e5-962c-aeddce73d142.png)

Det lykkeded dog ikke første gang jeg forsøgte, der kom den igennem men lavede 3 events? Jeg glemte at udfylde et felt 2 gange, så måske lavede den et event hver af de gange også? Det var cirka 10.45. De hedder I starten af ugen og ligger der stadig. 

Hov, hele stagingsiden er faktisk gået ned igen.... Det må være min fortjeneste:)

**Comment by ronan-mch** [comment]
ok, tak for hjælpen, jeg prøver at lave en løsning over weekenden.

**Comment by ronan-mch** [comment]
Hej, jeg har lavet en løsning, tror jeg. En del af det er at jeg nu viser de faste hvor dagene er sorteret efter hvor man er henne i ugen. Så i dag kommer søndag før mandag f.eks. De links nu går til event siderne frem for serie siderne. Lad mig lige ved hvad I mener.

**Comment by Siggik** [comment]
Gir go mening på den nye måde!

> 

    jeg har lavet det kortere - er det ikke nok?
    mht. fejlen kan jeg lige genskabe det og sitet virker ok for mig. Jeg prøver lige igen...

Tænker godt det kunne være kortere mellem mandag og den første event, så de holder bedre sammen

Men ovenstående kunne stadig være nice at få med og så #340.

**Comment by Siggik** [comment]
Jeg tester:

Fik fejlmedeleses her:
![screenshot from 2016-04-10 12 43 51](https://cloud.githubusercontent.com/assets/7570153/14409682/c55e40f4-ff1a-11e5-8015-76839e0d9f9a.png)

Da jeg trykkede på "slette eksisterende forekomster":

![screenshot from 2016-04-10 12 50 19](https://cloud.githubusercontent.com/assets/7570153/14409684/e609cc6a-ff1a-11e5-83a8-41e32e130fc7.png)

**Comment by Siggik** [comment]
Og den gamle bug kan jeg ikke genskabe. Nice.

**Comment by ronan-mch** [comment]
Ok, jeg har lavet en ny push til staging med mindre ændringer, bl.a. 

 - I mobil visning får man et link til en side med de faste begivenheder i stedet for at de bare er skjult.  
 - Afstanden mellem dagene og deres begivenheder i de faste er blevet mindre.
 - når en event på forsiden har mange categorier, bliver de sidste skjult med en `...` (p.t. ekspanderer eventen til en ekstra linje som bryder layout-en)

Hvis der ikke er nogle indvendinger, så laver jeg en advarsel på dukop.dk i morgen kl 12 og så opdaterer i morgen aften ved ni-tiden. @Siggik @tadoh

**Comment by Siggik** [comment]
Lyder perfekt!

**Comment by tadoh** [comment]
Nice!


-------- Original message --------

**Comment by ronan-mch** [comment]
Har lavet advarslen nu.
